services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./frontend:/var/www/html/frontend
    environment:
      DB_HOST: db
      DB_NAME: example
      DB_USER: user
      DB_PASSWORD: pass
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_DATABASE: example
    depends_on:
      - db

